var _id=0; function id(){ return _id++ };
var _pos=0; function pos(){ return _pos++ };

const choices = [
    { id: id(), pos: pos(), text: "2017 年进群" },
    { id: id(), pos: pos(), text: "经历过 G+ 时代" },
    { id: id(), pos: pos(), text: "记得 20 个群友外号" },
    { id: id(), pos: pos(), text: "去过 5 个群友的城市" },
    { id: id(), pos: pos(), text: "半夜出门刷 Po" },
    { id: id(), pos: pos(), text: "遭遇火车祥瑞" },
    { id: id(), pos: pos(), text: "会讲玉兰语" },
    { id: id(), pos: pos(), text: "被某安画进漫画" },
    { id: id(), pos: pos(), text: "成为群管理员" },
    { id: id(), pos: pos(), text: "喜欢的话题找到同好" },
    { id: id(), pos: pos(), text: "和群友起八" },
    { id: id(), pos: pos(), text: "10 人以上大型开饭" },
    { id: id(), pos: pos(), text: "和群友喝酒" },
    { id: id(), pos: pos(), text: "和初次见面的群友拼房" },
    { id: id(), pos: pos(), text: "和群旗合影" },
    { id: id(), pos: pos(), text: "互寄明信片" },
    { id: id(), pos: pos(), text: "一起连麦吹水" },
    { id: id(), pos: pos(), text: "联机打游戏" },
    { id: id(), pos: pos(), text: "和群友交换纪念 Key" },
    { id: id(), pos: pos(), text: "和群友交易物资" },
    { id: id(), pos: pos(), text: "制作自己的 biocard" },
    { id: id(), pos: pos(), text: "各种外语都学一点" },
    { id: id(), pos: pos(), text: "吃德国名菜 McRib" },
    { id: id(), pos: pos(), text: "在科隆户外烧烤" },
    { id: id(), pos: pos(), text: "在阿姆吃排骨" },
    { id: id(), pos: pos(), text: "在西班牙吃海鲜饭" },
    { id: id(), pos: pos(), text: "吃遍各国中餐馆" },
    { id: id(), pos: pos(), text: "约饭牌达到白金" },
    { id: id(), pos: pos(), text: "参观鸮博物馆" },
    { id: id(), pos: pos(), text: "给鸭梨家刷好评" },
    { id: id(), pos: pos(), text: "文明观熊" },
    { id: id(), pos: pos(), text: "一起蹲夏/冬令时" },
    { id: id(), pos: pos(), text: "一起跨年" },
    { id: id(), pos: pos(), text: "在很冷门的事上“群二”" },
    { id: id(), pos: pos(), text: "在群友家蹭住" },
    { id: id(), pos: pos(), text: "团购官方周边" },
    { id: id(), pos: pos(), text: "到剧情相关地标打卡" },
    { id: id(), pos: pos(), text: "和当地特工交朋友" },
    { id: id(), pos: pos(), text: "出国活动当天往返" },
    { id: id(), pos: pos(), text: "火车上写作业" },
    { id: id(), pos: pos(), text: "旧版 Scanner 留了很久" },
    { id: id(), pos: pos(), text: "在 Kaltenberg 搬砖" },
    { id: id(), pos: pos(), text: "乘坐王师傅专车" },
    { id: id(), pos: pos(), text: "挑战 GORUCK Stealth" },
    { id: id(), pos: pos(), text: "参加 OCF 捡垃圾" },
    { id: id(), pos: pos(), text: "集齐 GORUCK 三件套" },
    { id: id(), pos: pos(), text: "组团刷 Mission Day" },
    { id: id(), pos: pos(), text: "Mission Day 制霸" },
    { id: id(), pos: pos(), text: "和群友组队打 Anomaly" },
    { id: id(), pos: pos(), text: "赢得一场 Anomaly" },
    { id: id(), pos: pos(), text: "参加官方 After Party" },
    { id: id(), pos: pos(), text: "见到 NPC" },
    { id: id(), pos: pos(), text: "一起追 NL-1331" },
    { id: id(), pos: pos(), text: "找到 Deaddrop" },
    { id: id(), pos: pos(), text: "参与一次大新闻" },
    { id: id(), pos: pos(), text: "照片登上官方报道" },
    { id: id(), pos: pos(), text: "在活动中受伤" },
    { id: id(), pos: pos(), text: "出去玩遗失物品" },
    { id: id(), pos: pos(), text: "向群友学习旅行攻略" },
    { id: id(), pos: pos(), text: "欧洲地图了然于胸" },
    { id: id(), pos: pos(), text: "见过完好的巴黎圣母院" },
    { id: id(), pos: pos(), text: "放群友鸽子" },
    { id: id(), pos: pos(), text: "极限赶车成功" },
    { id: id(), pos: pos(), text: "穿越英吉利海峡" },
    { id: id(), pos: pos(), text: "乘坐通宵大巴" },
    { id: id(), pos: pos(), text: "在 Ingress 护照上盖章/和群友+10分" },
    { id: id(), pos: pos(), text: "把大群旗带回家" },
    { id: id(), pos: pos(), text: "参加线上 IFS" },
    { id: id(), pos: pos(), text: "玩 PPT 卡拉 OK" },
    { id: id(), pos: pos(), text: "IFS 拿过 0 AP" },
    { id: id(), pos: pos(), text: "因错过活动而遗憾" },
    { id: id(), pos: pos(), text: "满级重生" },
    { id: id(), pos: pos(), text: "单独见群友错过约饭牌" },
    { id: id(), pos: pos(), text: "收群友的二手货" },
    { id: id(), pos: pos(), text: "在公众号发表文章" },
    { id: id(), pos: pos(), text: "购买 CSAE 周边" },
    { id: id(), pos: pos(), text: "做过谈笑风生嘉宾" },
    { id: id(), pos: pos(), text: "和群友讨论学术" },
    { id: id(), pos: pos(), text: "吃鳗鱼饭时拍照发群里" },
    { id: id(), pos: pos(), text: "一起放风筝" },
    { id: id(), pos: pos(), text: "一起看世界杯" },
    { id: id(), pos: pos(), text: "吃过群友家的饭菜" },
    { id: id(), pos: pos(), text: "一起买家庭会员" },
    { id: id(), pos: pos(), text: "开好友房打麻将" },
    { id: id(), pos: pos(), text: "一起玩 Gamee 小游戏" },
    { id: id(), pos: pos(), text: "一起去看海" },
    { id: id(), pos: pos(), text: "薅铁路与航司羊毛" },
    { id: id(), pos: pos(), text: "聚会时不开Ingress" },
    { id: id(), pos: pos(), text: "悄悄喜欢群友" },
    { id: id(), pos: pos(), text: "给群友或自己过生日" },
    { id: id(), pos: pos(), text: "在社交网站上关注群友" },
    { id: id(), pos: pos(), text: "拥有 CSAE 群卡" },
    { id: id(), pos: pos(), text: "向外国友人介绍 CSAE" },
    { id: id(), pos: pos(), text: "保存群友的黑历史" },
    { id: id(), pos: pos(), text: "一起玩 Wordle" },
    { id: id(), pos: pos(), text: "收到群友送的礼物" },
    { id: id(), pos: pos(), text: "拥有看图识字表情包" },
    { id: id(), pos: pos(), text: "疫情期间线下见面" },
    { id: id(), pos: pos(), text: "会认不同国家的欧元/一起去爬山" },
    { id: id(), pos: pos(), text: "记得 CSAE 周年纪念日" },
];


const countries = {
    "冰岛is": [327, 211],
    "葡萄牙pt": [538, 1633],
    "爱尔兰ie": [585, 862],
    "法罗群岛fo": [706, 380],
    "直布罗陀gi": [706, 1794],
    "马恩岛im": [780, 856],
    "西班牙es": [923, 1585],
    "英国gb": [942, 914],
    "塞浦路斯cy": [2735, 1842],
    "科索沃xk": [2090, 1480],
    "拉脱维亚lv": [2211, 592],
    "阿尔巴尼亚al": [2011, 1614],
    "北马其顿mk": [2173, 1594],
    "梵蒂冈va": [1718, 1572],
    "黑山me": [1944, 1486],
    "摩尔多瓦md": [2481, 1203],
    "马耳他mt": [1706, 1827],
    "罗马尼亚ro": [2313, 1287],
    "乌克兰ua": [2375, 1045],
    "波兰pl": [1895, 880],
    "摩纳哥mc": [1281, 1423],
    "俄罗斯ru": [2643, 581],
    "奥地利at": [1643, 1159],
    "希腊gr": [2258, 1732],
    "芬兰fi": [2215, 379],
    "斯洛伐克sk": [1961, 1111],
    "瑞典se": [1785, 569],
    "挪威no": [1469, 478],
    "卢森堡lu": [1312, 1063],
    "荷兰nl": [1301, 846],
    "爱沙尼亚ee": [2371, 508],
    "圣马力诺sm": [1645, 1403],
    "立陶宛lt": [2283, 735],
    "列支敦士登li": [1501, 1133],
    "安道尔ad": [1064, 1467],
    "匈牙利hu": [2088, 1204],
    "丹麦dk": [1518, 667],
    "瑞士ch": [1391, 1225],
    "白俄罗斯by": [2450, 831],
    "克罗地亚hr": [1844, 1222],
    "土耳其tr": [2540, 1648],
    "斯洛文尼亚si": [1711, 1285],
    "比利时be": [1213, 956],
    "意大利it": [1498, 1327],
    "塞尔维亚rs": [2029, 1354],
    "保加利亚bg": [2276, 1465],
    "波黑ba": [1864, 1367],
    "德国de": [1537, 889],
    "捷克cz": [1747, 1043],
    "法国fr": [1154, 1147],
};

const countries_ordered = "ad,al,at,ba,be,bg,by,ch,cy,cz,de,dk,ee,es,fi,fo,fr,gb,gi,gr,hr,hu,ie,im,is,it,li,lt,lu,lv,mc,md,me,mk,mt,nl,no,pl,pt,ro,rs,ru,se,si,sk,sm,tr,ua,va,xk".split(",");


export { choices, countries, countries_ordered };
