module.exports = {
    SCALE_FACTOR: 300/96,

    RESOURCE_ICON_TILE_SIZE: 360,

    MENU_CHOICES_PER_ROW: 3,
    MENU_CHOICE_OSC_A: 0.1,
    MENU_CHOICE_OSC_T: 2000,

    RESULT_HEADER_HEIGHT_WIDTH_RATIO: 0.50,

    RESULT_ICONS_PER_ROW: 3,
    RESULT_ICONS_MARGIN_TO_CANVAS_WIDTH: 0.05,
    RESULT_ICON_ROW_HEIGHT_TO_GRID_SIZE: 1.35,
    RESULT_ICON_SIZE_TO_GRID_SIZE: 0.9,

    RESULT_LONG_PRESS_SAVE_TIME: 1000,
}
