var _id=0; function id(){ return _id++ };

const choices = [
    { id: id(), pos: 0, text: "2017 年进群" },
    { id: id(), pos: 1, text: "遭遇火车祥瑞" },
    { id: id(), pos: 0, text: "和群友们聚餐" },
    { id: id(), pos: 1, text: "和群旗合影" },
    { id: id(), pos: 0, text: "参加 GORUCK" },
    { id: id(), pos: 1, text: "在德国麦当劳吃 McRib" },
    { id: id(), pos: 1, text: "在科隆户外烧烤" },
    { id: id(), pos: 0, text: "在阿姆吃排骨" },
    { id: id(), pos: 1, text: "在苏黎世吃莲花园" },
    { id: id(), pos: 1, text: "住过群友家" },
    { id: id(), pos: 1, text: "参加线上 IFS" },
    { id: id(), pos: 0, text: "在公众号发表文章" },
    { id: id(), pos: 1, text: "和群友组队参加 Anomaly" },
    { id: id(), pos: 1, text: "在 Kaltenberg 搬砖" },
    { id: id(), pos: 1, text: "约饭牌黑了" },
    { id: id(), pos: 0, text: "打赢一场 Anomaly" },
    { id: id(), pos: 1, text: "夜刷 Mission Day" },
    { id: id(), pos: 1, text: "Mission Day 制霸" },
    { id: id(), pos: 1, text: "GORUCK 三连" },
    { id: id(), pos: 1, text: "参加 OCF" },
    { id: id(), pos: 1, text: "鸮过群友" },
    { id: id(), pos: 1, text: "会说玉兰语" },
    { id: id(), pos: 1, text: "找到冷门爱好同好" },
    { id: id(), pos: 1, text: "和群友联机打游戏" },
    { id: id(), pos: 1, text: "群友视频聊天" },
    { id: id(), pos: 1, text: "见到 Ingress 剧情人物" },
    { id: id(), pos: 1, text: "到剧情相关地标朝圣" },
    { id: id(), pos: 1, text: "群友聚会不开游戏" },
    { id: id(), pos: 1, text: "谈一场群内恋爱" },
    { id: id(), pos: 1, text: "穿越英吉利海峡" },
    { id: id(), pos: 1, text: "火车上赶作业" },
    { id: id(), pos: 1, text: "坐通宵大巴" },
    { id: id(), pos: 1, text: "追 NL1331" },
    { id: id(), pos: 1, text: "收到生日礼物" },
    { id: id(), pos: 1, text: "拥有 CSAE 周边" },
    { id: id(), pos: 1, text: "和当地特工成为朋友" },
    { id: id(), pos: 1, text: "向别人安利 Ingress 成功" },
    { id: id(), pos: 1, text: "和群友交换明信片" },
    { id: id(), pos: 1, text: "制作自己的 biocard" },
    { id: id(), pos: 1, text: "满级重生" },
];

module.exports = choices;
